apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::568560058349:role/GH-EKS-DEPLOY
      username: github-actions
      groups:
        - system:masters