name: Push to ECR with OIDC
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::568560058349:role/GitHubActions-ECR-Push
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        run: |
          docker build . -t demo-app -f  Dockerfile-liberica-multi-stage
          docker tag demo-app:latest ${{ steps.login-ecr.outputs.registry }}/demo-app:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/demo-app:latest