name: Push to ECR
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789:role/GitHub-Action-ECR-Push
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build . -t demo-app -f Dockerfile-liberica-multi-stage

      - name: Push image to Amazon ECR
        run: |
          docker tag demo-app:latest ${{ steps.login-ecr.outputs.registry }}/demo-app:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/demo-app:latest