name: Deploy to ECS
on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-1
  ECR_REPO: demo-app
  ECS_CLUSTER: demo-app-cluster
  ECS_SERVICE: demo-app-service
  ECS_TASK_FAMILY: demo-app-task

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::568560058349:role/GH-ECS-DEPLOY
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-liberica-multi-stage
          push: false
          load: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Push Docker image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest

      - name: Move cache for next build
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # --- ECS Deployment Steps ---
      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_FAMILY }} \
            --query taskDefinition > task-def.json

      - name: Update task definition with new image
        id: task-def
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest"
          jq --arg IMAGE "$IMAGE" '.containerDefinitions[0].image=$IMAGE' task-def.json > new-task-def.json

      - name: Register new task definition revision
        id: register-task
        run: |
          NEW_REVISION=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.revision" --output text)
          echo "NEW_REVISION=$NEW_REVISION" >> $GITHUB_ENV

      - name: Deploy new revision to ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.ECS_TASK_FAMILY }}:$NEW_REVISION \
            --force-new-deployment